-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 17:08:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SwimInGreeceDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SwimInGreeceDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SwimInGreeceDB` DEFAULT CHARACTER SET utf8 ;
USE `SwimInGreeceDB` ;

-- -----------------------------------------------------
-- Table `SwimInGreeceDB`.`Swimmers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SwimInGreeceDB`.`Swimmers` (
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Fullname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SwimInGreeceDB`.`Organisers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SwimInGreeceDB`.`Organisers` (
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Fullname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SwimInGreeceDB`.`Tours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SwimInGreeceDB`.`Tours` (
  `Name` VARCHAR(45) NOT NULL,
  `Organiser` VARCHAR(45) NOT NULL,
  `Start` DATETIME NOT NULL,
  `End` DATETIME NOT NULL,
  `TotalLength` FLOAT NOT NULL,
  PRIMARY KEY (`Name`, `Organiser`),
  INDEX `Fk_Tours_org_idx` (`Organiser` ASC) VISIBLE,
  CONSTRAINT `Fk_Tours_org`
    FOREIGN KEY (`Organiser`)
    REFERENCES `SwimInGreeceDB`.`Organisers` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SwimInGreeceDB`.`Swims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SwimInGreeceDB`.`Swims` (
  `Place` VARCHAR(45) NOT NULL,
  `Tour` VARCHAR(45) NOT NULL,
  `Organiser` VARCHAR(45) NOT NULL,
  `Length` FLOAT NOT NULL,
  PRIMARY KEY (`Place`, `Tour`, `Organiser`),
  INDEX `Fk_swims_tour_idx` (`Tour` ASC) VISIBLE,
  INDEX `Fk_swims_org_idx` (`Organiser` ASC) VISIBLE,
  CONSTRAINT `Fk_swims_tour`
    FOREIGN KEY (`Tour`)
    REFERENCES `SwimInGreeceDB`.`Tours` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_swims_org`
    FOREIGN KEY (`Organiser`)
    REFERENCES `SwimInGreeceDB`.`Organisers` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SwimInGreeceDB`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SwimInGreeceDB`.`Reviews` (
  `IdReview` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Body` VARCHAR(100) NULL,
  `Rating` INT NOT NULL,
  PRIMARY KEY (`IdReview`, `Username`),
  INDEX `Fk_bookings_swimmer_idx` (`Username` ASC) VISIBLE,
  CONSTRAINT `Fk_bookings_swimmer`
    FOREIGN KEY (`Username`)
    REFERENCES `SwimInGreeceDB`.`Swimmers` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SwimInGreeceDB`.`Bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SwimInGreeceDB`.`Bookings` (
  `Swimmer` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Org` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Swimmer`, `Name`, `Org`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SwimInGreeceDB`.`PastBookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SwimInGreeceDB`.`PastBookings` (
  `Swimmer` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Org` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Swimmer`, `Name`, `Org`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SwimInGreeceDB`.`Swimmers`
-- -----------------------------------------------------
START TRANSACTION;
USE `SwimInGreeceDB`;
INSERT INTO `SwimInGreeceDB`.`Swimmers` (`Username`, `Password`, `Fullname`) VALUES ('Sw1', '1', 'Andrea Tsilo');
INSERT INTO `SwimInGreeceDB`.`Swimmers` (`Username`, `Password`, `Fullname`) VALUES ('Sw2', '1', 'Sara Luciani');

COMMIT;


-- -----------------------------------------------------
-- Data for table `SwimInGreeceDB`.`Organisers`
-- -----------------------------------------------------
START TRANSACTION;
USE `SwimInGreeceDB`;
INSERT INTO `SwimInGreeceDB`.`Organisers` (`Username`, `Password`, `Fullname`) VALUES ('Org1', '1', 'Mario Rossi');
INSERT INTO `SwimInGreeceDB`.`Organisers` (`Username`, `Password`, `Fullname`) VALUES ('Org2', '1', 'Giuseppe Verdi');
INSERT INTO `SwimInGreeceDB`.`Organisers` (`Username`, `Password`, `Fullname`) VALUES ('Org3', '1', 'Luca Bianchi');

COMMIT;

